framework:
    secret: "I'm not sure what the purpose of this secret is."

aws:
    version: latest
    region: us-west-2
    credentials:
        key: not-a-real-key
        secret: "@@not-a-real-secret" # this will be escaped as '@not-a-real-secret'
    DynamoDb:
        region: us-west-2
    S3:
        version: '2006-03-01'
    Sqs:
        credentials: "@a_service"
    Lambda:
        region: us-west-1

services:
    'Aws\DynamoDb\DynamoDbClient':
        class: Aws\DynamoDb\DynamoDbClient
        arguments:
            -
                region: eu-west-2
                version: '2012-08-10'

    'Aws\TranscribeService\TranscribeServiceClient':
        class: Aws\TranscribeService\TranscribeServiceClient
        arguments:
            -
                region: us-west-2
    'Aws\S3\S3Client':
        class: Aws\S3\S3Client
        arguments:
            -
                region: us-west-2
    a_service:
        class: Aws\Credentials\Credentials
        arguments:
            - a-different-fake-key
            - a-different-fake-secret

    test_service:
        class: Aws\Symfony\fixtures\TestService
        public: true
        arguments:
            - '@aws.s3'
            - '@aws.lambda'
