index:
    path: /
    controller: App\Controller\TranscribeController::index
app_transcribe_number:
        path: /number
        controller: App\Controller\TranscribeController::number

app_transcribe_get_jobs:
        path: /get_jobs
        controller: App\Controller\TranscribeController::getTranscriptions

app_transcribe_get_job:
        path: /get_job/{job_name}
        controller: App\Controller\TranscribeController::getTranscription

app_transcribe_get_job_json:
        path: /get_job_json/{job_name}
        controller: App\Controller\TranscribeController::getTranscriptJson

app_transcribe_start_job:
        path: /startJob
        controller: App\Controller\TranscribeController::startJobFromDrupal
